- name: Deploy webapp
  become: true
  copy:
    src: ../webapp/go/isupipe
    dest: /home/isucon/webapp/go/
  notify: restart_webapp
- name: Deploy init files
  become: true
  copy:
    src: "{{ item }}"
    dest: /home/isucon/webapp/sql/
  with_items:
    - ../webapp/sql/init.sh
    - ../webapp/sql/init.sql

- name: Deploy sql files
  become: true
  copy:
    src: "{{ item }}"
    dest: /home/isucon/webapp/sql/initdb.d/
  with_items:
    - ../webapp/sql/initdb.d/00_create_database.sql
    - ../webapp/sql/initdb.d/10_schema.sql

- name: Deploy pdns
  become: true
  copy:
    src: "{{ item }}"
    dest: /home/isucon/webapp/pdns/
  notify:
    - apply-pdns
    - restart-pdns
  with_items:
    - ../webapp/pdns/init_zone.sh
    - ../webapp/pdns/named.conf
    - ../webapp/pdns/u.isucon.dev.zone
