- name: Install alp
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/isucon/.local/go/bin"
  shell:
    chdir: /home/isucon/
    cmd: "{{ item }}"
  with_items:
    - "go install github.com/tkuchiki/alp/cmd/alp@latest"
