- name: Clone pprotein
  become: true
  git:
    repo: https://github.com/rinchsan/pprotein.git
    dest: /home/isucon/pprotein
- name: Build pprotein
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/home/isucon/local/node/bin:/home/isucon/local/golang/bin"
  shell:
    chdir: /home/isucon/pprotein/
    cmd: "{{ item }}"
  with_items:
    - "make pprotein-agent"
