- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - graphviz
    - gv
    - npm
- name: Clone pprotein
  become: true
  git:
    repo: https://github.com/rinchsan/pprotein.git
    dest: /home/isucon/pprotein
- name: Build pprotein
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/home/isucon/local/node/bin:/home/isucon/local/golang/bin"
  shell:
    chdir: /home/isucon/pprotein/
    cmd: "{{ item }}"
  with_items:
    - "npm --prefix view ci"
    - "npm --prefix view run build"
    - "make pprotein"
