- hosts: pprotein
  remote_user: ubuntu
  tasks:
    - import_role:
        name: alp
        tasks_from: install
    - import_role:
        name: slp
        tasks_from: install
    - import_role:
        name: pprotein
        tasks_from: build
    - import_role:
        name: pprotein
        tasks_from: deploy
